post_id: 2026-01-05T14-21-21-turning-a-stochastic-coder-into-a-deterministic-collaborator
title: Turning a Stochastic Coder into a Deterministic Collaborator
author: Andreas Atle
created_at: 2026-01-05 14:21:21+00:00
status: published
