post_id: 2026-01-12T20-06-58Z__45803b
title: The Ecological and Cultural Impact of Bees, Honey, and Applebee's
author: Andreas Atle
created_at: 2026-01-12 20:06:58+00:00
status: draft
revisions:
- revision_id: 1
  timestamp: '2026-01-12T20:07:21+00:00'
  delta_type: title_changed
  delta_payload:
    new_title: The Ecological and Cultural Impact of Bees, Honey, and Applebee's
  actor:
    type: human
    id: Andreas Atle
  status: applied
