post_id: 2026-01-14T01-43-54Z__d7dfff
title: null
author: Andreas Atle
created_at: 2026-01-14 01:43:54+00:00
status: draft
revisions:
- revision_id: 1
  timestamp: '2026-01-14T01:44:32+00:00'
  delta_type: content_free_edit
  delta_payload:
    changed_chunks:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    before_hash: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    after_hash: dde9ffb43b212fbf6a262452190a661becf0f7c6a33c0ce70f0768c4e899f038
  actor:
    type: generator
    id: Andreas Atle
  status: applied
